# Generated by Django 5.0.6 on 2024-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pizzas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("tamanio", models.CharField(max_length=200)),
                ("precio", models.IntegerField()),
            ],
            options={
                "db_table": "pizza",
            },
        ),
    ]
